version: '3.8'

services:
  web:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    container_name: drqa-backend
    command: bash -c 'uvicorn backend.app.main:app --host 0.0.0.0 --reload --port=8000'
    volumes:
      - .:/app
    ports:
      - 8001:8000
    env_file:
      - ./backend/app/.env